#!/usr/bin/env bash
# Configures /redirect_me

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
echo 'Hello World!' | sudo tee /var/www/html/index.html

string="\tlocation / {"
replace="\tlocation /redirect_me {\n\t\treturn 301 \$scheme://https://www.youtube.com/watch?v=TWTfhyvzTx0;\n\t}\n\n\tlocation / {"
sudo sed -i "s@^$string@$replace@" /etc/nginx/sites-available/default

sudo service nginx restart
