#!/usr/bin/env bash
# Configures /redirect_me

sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'
target="^\tlocation / {"
replace="\tlocation /redirect_me {\n\t\treturn 301 \$scheme://youtu.be/TWTfhyvzTx0;\n\t}\n\n\tlocation / {"
sudo sed -i "s@$target@$replace@" /etc/nginx/sites-available/default
sudo service nginx restart
