#!/usr/bin/env bash
# Configures /redirect_me

sudo apt-get -y install nginx
echo "Hello World" | sudo tee /var/www/html/index.nginx-debian.html
target="^\tlocation / {"
replace="\tlocation /redirect_me {\n\t\treturn 301 \$scheme://youtu.be/TWTfhyvzTx0;\n\t}\n\n\tlocation / {"
sudo sed -i "s@$target@$replace@" /etc/nginx/sites-available/default
sudo service nginx restart
