#!/usr/bin/env bash
#  Error Page 404

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx

find="^\tlocation / {"
replace="\tlocation /redirect_me {\n\t\treturn 301 \$scheme://youtube.com;\n\t}\n\n\tlocation / {"
replace404="\terror_page 404 /error404.html;\n\n\tlocation / {"

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error404.html

sudo sed -i "s@$find@$replace@" /etc/nginx/sites-available/default
sudo sed -i "s@$find@$replace404@" /etc/nginx/sites-available/default

sudo service nginx restart
sudo service nginx reload