#!/usr/bin/env bash
##Story of /etc/passwd

while read -r line;
do
    echo "The user $USERNAME is part of the $GROUPS gang, lives in $HOME and rides COMMAND/SHELL. $UID's place is protected by the passcode PASSWORD, more info about the user here: USER ID INFO"
    done < /etc/passwd
