#!/usr/bin/env bash
# Installs HAProxy

sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y install haproxy=2.5.\*

string="\nfrontend myfrontend
\n\tbind *:80
\n\tstats uri /haproxy?stats
\n\tdefault_backend myservers
\n\nbackend myservers
\n\tbalance roundrobin
\n\tserver 3599-web-01 3.90.188.172:80
\n\tserver 3599-web-02 54.243.24.124:80"

sudo echo -e $string | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart
